MenuCommand class
AY2122S1-CS2113-T13-2/tp pull request #42
Opened 2021-10-08 17:56 UTC by thaddyyz

left original menu class for reference, remove it if not needed. Additionally can identify a suitable place to call GetMenu as it should only be called once when the program is running.

2021-10-09 01:33 UTC, andrewtkh1 requested changes
View comments in code.

2021-10-09 01:33 UTC, andrewtkh1 commented on src/main/java/seedu/duke/MenuCommand.java
> +        Ui.printMenuHeader();
I believe the printing of header & the body should be in a `execute()` function.
The other comment below shows what I mean, or you can refer to the link below to see the deleteCommand class.

E.g) https://github.com/AY2122S1-CS2113-T13-2/tp/blob/master/src/main/java/seedu/duke/DeleteCommand.java

2021-10-09 01:33 UTC, andrewtkh1 commented on src/main/java/seedu/duke/MenuCommand.java
> +
```suggestion
@Override
public void execute() {
    Ui.printMenuHeader();
    for (int i = 0; i < foodList.size(); i++) {
            Ui.printMenu(i + 1, foodList.get(i), priceList.get(i));
    }
}
```

2021-10-09 01:33 UTC, andrewtkh1 commented on src/main/java/seedu/duke/Ui.java
> +    static String line = "--------------------------------------------------";
Perhaps can consider changing this to private static final?

2021-10-09 01:33 UTC, andrewtkh1 commented on src/main/java/seedu/duke/MenuCommand.java
> +            priceList.add(Double.parseDouble(data.substring(data.indexOf("|") + 1)));
Would it be better to not deeply nest the code? Might help to make it more readable.

2021-10-10 03:56 UTC, thaddyyz commented on src/main/java/seedu/duke/MenuCommand.java
> +            priceList.add(Double.parseDouble(data.substring(data.indexOf("|") + 1)));
I still need this as a while loop but I put the entire loop in a separate function to improve readability

2021-10-10 04:09 UTC, merged